<?php

declare(strict_types=1);

namespace Yab\LaravelApiContract\Generators\Client;

use Yab\LaravelApiContract\Contracts\ApiContractContract;
use Yab\LaravelApiContract\Contracts\ClientGeneratorContract;
use Yab\LaravelApiContract\Services\Client\ClientBuilder;
use Yab\LaravelApiContract\Services\Contract\EndpointDefinition;
use Yab\LaravelApiContract\Support\TypeScriptTypeMapper;

class ClientGenerator implements ClientGeneratorContract
{
    private const API_PREFIX = 'api';

    public function __construct(
        private readonly ClientBuilder $builder,
        private readonly TypeScriptTypeMapper $mapper,
    ) {
    }

    /**
     * @return array<int, array{filename: string, content: string}>
     */
    public function generate(ApiContractContract $contract): array
    {
        $files = [];

        $groups = $this->groupEndpointsByResource($contract->endpoints());

        if ($groups === []) {
            return $files;
        }

        $services = [];

        foreach ($groups as $resource => $endpoints) {
            $serviceFunctions = [];

            foreach ($endpoints as $endpoint) {
                $functionDef = $this->buildFunctionDefinition($endpoint, $resource);

                $serviceFunctions[] = $functionDef['definition'];
            }

            if ($serviceFunctions === []) {
                continue;
            }

            $services[$resource] = $serviceFunctions;
        }

        $files[] = [
            'filename' => 'client.ts',
            'content' => $this->buildClientFile($contract),
        ];

        foreach ($services as $resource => $functions) {
            $this->builder->reset();
            $this->builder->comment('Auto-generated by laravel-api-contract');
            $this->builder->comment('Do not edit manually');
            $this->builder->blankLine();
            $this->builder->line("import { api } from './client';");
            $this->builder->blankLine();

            $this->builder->serviceObject($resource . 'Service', $functions);

            $files[] = [
                'filename' => "{$resource}.service.ts",
                'content' => $this->builder->getOutput(),
            ];
        }

        return $files;
    }

    /**
     * @param array<int, EndpointDefinition> $endpoints
     *
     * @return array<string, array<int, EndpointDefinition>>
     */
    private function groupEndpointsByResource(array $endpoints): array
    {
        $groups = [];

        foreach ($endpoints as $endpoint) {
            $resource = $this->extractResourceName($endpoint->uri());

            if ($resource === null) {
                continue;
            }

            $groups[$resource][] = $endpoint;
        }

        return $groups;
    }

    private function extractResourceName(string $uri): ?string
    {
        $parts = explode('/', $uri);

        $segments = array_values(array_filter($parts, static fn (string $part): bool => $part !== ''));

        if ($segments === []) {
            return null;
        }

        if ($segments[0] === self::API_PREFIX) {
            if (isset($segments[1])) {
                $resource = $segments[1];

                if (str_starts_with($resource, '{')) {
                    return null;
                }

                return $this->singularize($resource);
            }

            return null;
        }

        $resource = $segments[0];

        if (str_starts_with($resource, '{')) {
            return null;
        }

        return $this->singularize($resource);
    }

    private function singularize(string $word): string
    {
        if (str_ends_with($word, 'ies')) {
            return substr($word, 0, -3) . 'y';
        }

        if (
            str_ends_with($word, 'ses') || str_ends_with($word, 'xes') ||
            str_ends_with($word, 'ches') || str_ends_with($word, 'shes')
        ) {
            return substr($word, 0, -2);
        }

        if (str_ends_with($word, 's') && !str_ends_with($word, 'ss')) {
            return substr($word, 0, -1);
        }

        return $word;
    }

    /**
     * @return array<string, string>
     */
    private function buildFunctionDefinition(EndpointDefinition $endpoint, string $resource): array
    {
        $hasPathParams = $endpoint->parameters() !== [];
        $isCollection = !$hasPathParams && $endpoint->method() === 'GET';

        $functionName = $this->buildFunctionName($endpoint->method(), $resource, $isCollection);
        $params = [];
        $urlParams = [];

        foreach ($endpoint->parameters() as $param) {
            $params[] = "{$param}: number";
            $urlParams[] = $param;
        }

        $requestDefinition = $endpoint->request();
        $requestType = null;
        $requestParam = null;

        if ($requestDefinition !== null) {
            $requestType = $this->mapper->requestToInterface($requestDefinition->className());
            $params[] = "data: {$requestType}";
            $requestParam = 'data';
        }

        $resourceDefinition = $endpoint->response();
        $responseType = null;

        if ($resourceDefinition !== null) {
            $resourceType = $this->mapper->relationToInterface($resourceDefinition->resourceClass());
            $responseType = $isCollection ? "{$resourceType}[]" : $resourceType;
        }

        if ($responseType === null && $endpoint->method() === 'DELETE') {
            $responseType = 'void';
        }

        $httpMethod = strtolower($endpoint->method());

        $body = $this->builder->buildApiCallBody(
            httpMethod: $httpMethod,
            path: '/' . $endpoint->uri(),
            responseType: $responseType,
            urlParams: $urlParams,
            requestParam: $requestParam,
        );

        $returnType = $responseType ?? 'void';

        $fnDef = $this->builder->buildAsyncFunction(
            name: $functionName,
            params: $params,
            returnType: $returnType,
            body: $body,
        );

        return [
            'name' => $functionName,
            'definition' => $fnDef,
        ];
    }

    private function buildFunctionName(string $method, string $resource, bool $isCollection): string
    {
        $ucResource = ucfirst($resource);

        return match ($method) {
            'GET' => $isCollection ? "get{$ucResource}s" : "get{$ucResource}",
            'POST' => "create{$ucResource}",
            'PUT' => "update{$ucResource}",
            'PATCH' => "patch{$ucResource}",
            'DELETE' => "delete{$ucResource}",
            default => "{$method}{$ucResource}",
        };
    }

    private function buildClientFile(ApiContractContract $contract): string
    {
        $this->builder->reset();
        $this->builder->comment('Auto-generated by laravel-api-contract');
        $this->builder->comment('Do not edit manually');
        $this->builder->blankLine();
        $this->builder->line("import axios from 'axios';");
        $this->builder->blankLine();
        $this->builder->line('export const api = axios.create({');
        $this->builder->indent();
        $this->builder->line("baseURL: '/api',");
        $this->builder->outdent();
        $this->builder->line('});');
        $this->builder->blankLine();

        $auth = $contract->authentication();

        $this->builder->line("api.defaults.headers.common['Accept'] = 'application/json';");
        $this->builder->line("api.defaults.headers.common['Content-Type'] = 'application/json';");
        $this->builder->blankLine();

        if ($auth === 'sanctum') {
            $this->builder->line('// Sanctum CSRF cookie support');
            $this->builder->line('api.defaults.withCredentials = true;');
            $this->builder->line('api.defaults.withXSRFToken = true;');
        } elseif ($auth === 'bearer' || $auth === 'passport' || $auth === 'jwt') {
            $this->builder->comment('Add bearer token interceptor');
            $this->builder->line('api.interceptors.request.use((config) => {');
            $this->builder->indent();
            $this->builder->line("const token = localStorage.getItem('auth_token');");
            $this->builder->blankLine();
            $this->builder->line('if (token) {');
            $this->builder->indent();
            $this->builder->line('config.headers.Authorization = `Bearer ${token}`;');
            $this->builder->outdent();
            $this->builder->line('}');
            $this->builder->blankLine();
            $this->builder->line('return config;');
            $this->builder->outdent();
            $this->builder->line('});');
        }

        return $this->builder->getOutput();
    }
}
