<?php

declare(strict_types=1);

namespace Yab\LaravelApiContract\Generators\TypeScript;

use Yab\LaravelApiContract\Contracts\ApiContractContract;
use Yab\LaravelApiContract\Contracts\TypeScriptGeneratorContract;
use Yab\LaravelApiContract\Services\DTO\ResourceDefinition;
use Yab\LaravelApiContract\Services\DTO\RequestDefinition;
use Yab\LaravelApiContract\Services\DTO\ResponseField;
use Yab\LaravelApiContract\Services\DTO\ValidationField;
use Yab\LaravelApiContract\Services\TypeScript\TypeScriptBuilder;
use Yab\LaravelApiContract\Support\TypeScriptTypeMapper;

class TypeScriptGenerator implements TypeScriptGeneratorContract
{
    public function __construct(
        private readonly TypeScriptBuilder $builder,
        private readonly TypeScriptTypeMapper $mapper,
    ) {
    }

    /**
     * @return array<int, array{filename: string, content: string}>
     */
    public function generate(ApiContractContract $contract): array
    {
        $files = [];
        $interfaces = [];
        $requestInterfaces = [];

        foreach ($contract->endpoints() as $endpoint) {
            $response = $endpoint->response();

            if ($response !== null) {
                $interfaceName = $this->interfaceNameForResource($response);

                if (!isset($interfaces[$interfaceName])) {
                    $interfaces[$interfaceName] = $this->buildResourceInterface($response);
                }
            }

            $request = $endpoint->request();

            if ($request !== null) {
                $interfaceName = $this->interfaceNameForRequest($request);

                if (!isset($requestInterfaces[$interfaceName])) {
                    $requestInterfaces[$interfaceName] = $this->buildRequestInterface($request);
                }
            }
        }

        if ($interfaces === [] && $requestInterfaces === []) {
            return $files;
        }

        $this->builder->reset();
        $this->builder->comment('Auto-generated by laravel-api-contract');
        $this->builder->comment('Do not edit manually');
        $this->builder->blankLine();

        foreach ($interfaces as $name => $properties) {
            $this->builder->interface($name, $properties);
            $this->builder->blankLine();
        }

        foreach ($requestInterfaces as $name => $properties) {
            $this->builder->interface($name, $properties);
            $this->builder->blankLine();
        }

        $files[] = [
            'filename' => 'api.ts',
            'content' => $this->builder->getOutput(),
        ];

        return $files;
    }

    /**
     * @return array<string, string>
     */
    private function buildResourceInterface(ResourceDefinition $resource): array
    {
        $properties = [];

        foreach ($resource->fields() as $field) {
            $properties[$field->name()] = $this->fieldToTypeScript($field);
        }

        return $properties;
    }

    /**
     * @return array<string, string>
     */
    private function buildRequestInterface(RequestDefinition $request): array
    {
        $properties = [];

        foreach ($request->fields() as $field) {
            $properties[$field->name()] = $this->validationFieldToTypeScript($field);
        }

        return $properties;
    }

    private function fieldToTypeScript(ResponseField $field): string
    {
        if ($field->isRelationship()) {
            $refName = $this->mapper->relationToInterface($field->relationClass() ?? '');

            if ($field->collection()) {
                $type = "{$refName}[]";
            } else {
                $type = $refName;
            }
        } else {
            $type = $this->mapper->toTypeScript($field->type());
        }

        if ($field->nullable()) {
            $type = TypeScriptBuilder::nullable($type, true);
        }

        return $type;
    }

    private function validationFieldToTypeScript(ValidationField $field): string
    {
        $type = $this->mapper->toTypeScript($field->type());

        if (!$field->required()) {
            $type = TypeScriptBuilder::nullable($type, true);
        }

        return $type;
    }

    private function interfaceNameForResource(ResourceDefinition $resource): string
    {
        return $this->mapper->relationToInterface($resource->resourceClass());
    }

    private function interfaceNameForRequest(RequestDefinition $request): string
    {
        return $this->mapper->requestToInterface($request->className());
    }
}
